export const DEFAULT_CATEGORIES = [
  { name: 'Restaurants & Food', slug: 'restaurants', icon: 'Utensils', description: 'Dining, catering, food trucks, bakeries, and more' },
  { name: 'Beauty & Wellness', slug: 'beauty-wellness', icon: 'Sparkles', description: 'Salons, spas, barbershops, wellness centers' },
  { name: 'Professional Services', slug: 'professional-services', icon: 'Briefcase', description: 'Legal, consulting, accounting, marketing' },
  { name: 'Retail & Shopping', slug: 'retail', icon: 'ShoppingBag', description: 'Clothing, gifts, specialty shops, boutiques' },
  { name: 'Health & Medical', slug: 'health-medical', icon: 'HeartPulse', description: 'Doctors, dentists, clinics, therapists' },
  { name: 'Home Services', slug: 'home-services', icon: 'Home', description: 'Cleaning, repairs, landscaping, contractors' },
  { name: 'Automotive', slug: 'automotive', icon: 'Car', description: 'Repair shops, detailing, dealerships' },
  { name: 'Entertainment', slug: 'entertainment', icon: 'Music', description: 'Events, music, arts, recreation' },
  { name: 'Education & Training', slug: 'education', icon: 'GraduationCap', description: 'Tutoring, schools, coaching, workshops' },
  { name: 'Real Estate', slug: 'real-estate', icon: 'Building', description: 'Agents, property management, development' },
  { name: 'Financial Services', slug: 'financial', icon: 'Landmark', description: 'Banking, insurance, investments, tax prep' },
  { name: 'Technology', slug: 'technology', icon: 'Laptop', description: 'IT services, software, web development' },
  { name: 'Arts & Culture', slug: 'arts-culture', icon: 'Palette', description: 'Galleries, artists, cultural organizations' },
  { name: 'Nonprofit & Community', slug: 'nonprofit', icon: 'HeartHandshake', description: 'Charities, community organizations, advocacy' },
];

export const CATEGORY_ICONS = {
  'restaurants': 'Utensils',
  'beauty-wellness': 'Sparkles',
  'professional-services': 'Briefcase',
  'retail': 'ShoppingBag',
  'health-medical': 'HeartPulse',
  'home-services': 'Home',
  'automotive': 'Car',
  'entertainment': 'Music',
  'education': 'GraduationCap',
  'real-estate': 'Building',
  'financial': 'Landmark',
  'technology': 'Laptop',
  'arts-culture': 'Palette',
  'nonprofit': 'HeartHandshake',
};
